name: lsfr Test
description: Test coding challenges with lsfr

inputs:
  working-directory:
    description: Directory containing lsfr.yaml
    required: false
    default: '.'
  lsfr-version:
    description: Version of lsfr to install
    required: false
    default: 'v0.1.0'

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Cache lsfr
      uses: actions/cache@v5
      id: cache-lsfr
      with:
        path: ~/go/bin/lsfr
        key: lsfr-${{ runner.os }}-${{ runner.arch }}-${{ inputs.lsfr-version }}

    - name: Install lsfr
      if: steps.cache-lsfr.outputs.cache-hit != 'true'
      shell: bash
      run: go install github.com/st3v3nmw/lsfr/cmd/lsfr@${{ inputs.lsfr-version }}

    - name: Run lsfr tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ github.action_path }}/test.sh
