name: Test
description: Test coding challenges with lc

inputs:
  working-directory:
    description: Directory containing lc.state
    required: false
    default: '.'
  lc-version:
    description: Version of lc to install
    required: false
    default: 'v0.2.0'

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Install lc
      shell: bash
      run: go install github.com/littleclusters/lc/cmd/lc@${{ inputs.lc-version }}

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ github.action_path }}/test.sh
