name: Test
description: Test coding challenges with clstr

inputs:
  working-directory:
    description: Directory containing clstr.yaml
    required: false
    default: '.'
  clstr-version:
    description: Version of clstr to install
    required: false
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version: '1.26'

    - name: Install clstr
      shell: bash
      run: go install github.com/clstr-io/clstr/cmd/clstr@${{ inputs.clstr-version }}

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ github.action_path }}/test.sh
